services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: dragonflydb
    ulimits:
      memlock: -1
    # ports:
    #  - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    network_mode: "host"
    command: dragonfly --logtostderr --maxclients 300000 --minloglevel 0 --requirepass ${REDIS_PASSWORD}
    volumes:
      - dragonflydata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "--no-auth-warning", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
volumes:
  dragonflydata:
